steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - artifacts
      - go
      - upload
      - --project=digital-node-1176
      - --location=australia-southeast2
      - --repository=bmwadforth-go
      - --module-path=github.com/bmwadforth/galaxy
      - --version=$TAG_NAME
    entrypoint: gcloud
    id: publish

options:
  machineType:  N1_HIGHCPU_8