steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'sh'
      - '-c'
      - 'apt-get install -y google-cloud-cli-package-go-module'
    id: prepare

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - artifacts
      - go
      - upload
      - --project=digital-node-1176
      - --location=australia-southeast2
      - --repository=bmwadforth-go
      - --module-path=github.com/bmwadforth/galaxy
      - --version=$TAG_NAME
      - --source=..
    id: publish
    waitFor:
      - prepare

options:
  machineType:  N1_HIGHCPU_8