name: Build and Release
on:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write
  pages: write
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.22

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./test/...

  release-please:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      pr_created: ${{ steps.release.outputs.prs_created }}
      pr_number: ${{ steps.release.outputs.pr.number }}
      release_version: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: go